version: '3'
services:
  app_bac:
    container_name: app_bac
    build: .
    image: app:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: appDB_bac
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '2337:1337'
    networks:
      - app
    depends_on:
      - appDB_bac
      
  appDB_bac:
    container_name: appDB_bac
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - app-data:/var/lib/mysql
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '3307:3306'
    networks:
      - app
      
  phpmyadmin_bac:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_bac
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    ports:
      - "8082:80"
    networks:
      - app
    depends_on:
      - appDB_bac

  appsmith:
    image: index.docker.io/appsmith/appsmith-ee:v1.9.50
    container_name: appsmith_bac
    ports:
      - "8091:80"
      - "9443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    networks:
      - app


volumes:
  app-data:

networks:
  app:
    name: App
    driver: bridge
