/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import email from "@strapi/plugin-email/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-versioning": contentVersioning,
    "strapi-cloud": strapiCloud,
    email: email,
    i18n: i18N,
    "users-permissions": usersPermissions,
  },
});